version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: zeek-elasticsearch-1 # Adicionado para consistência
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastinet
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: zeek-kibana-1 # Adicionado para consistência
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.reporting.enabled=false
    ports:
      - "5601:5601"
    networks:
      - elastinet

  filebeat:
    # Se você tem um Dockerfile para o filebeat, use 'build'
    # build:
    #   context: ./filebeat
    #   dockerfile: Dockerfile
    # Se não, use 'image'
    image: docker.elastic.co/beats/filebeat:7.10.2
    container_name: zeek-filebeat-1 # Adicionado para consistência
    user: root
    depends_on:
      - kibana
    volumes:
      # Volume para os logs do Zeek
      - pcap:/pcap:ro
  # (Removido bind mount do filebeat.yml para evitar problemas de permissão)
      # Volume compartilhado com o HMI para pegar os logs de ataque
      - ../attack-logs:/attack-logs:ro
    networks:
      - elastinet

  zeek:
    build:
      context: ./zeek/elastic
      dockerfile: Dockerfile
    container_name: zeek-zeek-1 # Adicionado para consistência
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - pcap:/pcap
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # O network_mode: "host" é poderoso, mas pode complicar a comunicação
    # entre contêineres. Mantido conforme o original.
    network_mode: "host"
    # ATENÇÃO: 'enp0s3' é o nome de uma interface de rede.
    # Certifique-se de que é a interface correta que você quer monitorar.
    entrypoint: ["zeek", "-i", "enp0s3", "local"]

networks:
  elastinet:
    driver: bridge
    # Removido o 'name' e 'ipam' para deixar o Docker gerenciar,
    # o que evita conflitos e é mais simples.
    # Se precisar de IP fixo, pode adicionar de volta.

volumes:
  pcap: {}
  esdata: {}
