version: "3.9"
services:
  ctf_service:
    image: alpine
    container_name: ctf_flag_service
    # O comando abaixo abre a porta 1337 e envia o conteúdo do ficheiro flag1.sh
    command: sh -c "while true; do { cat /flag1.sh; } | nc -l -p 1337; done"
    volumes:
      # Mapeia o seu ficheiro local flag1.sh para dentro do contentor
      - ./flag1.sh:/flag1.sh
    ports:
      - "1337:1337"
    networks:
      - phynet
      - icsnet

networks:
  phynet:
    external: true
  icsnet:
    external: true
